name: pensa
description: Expense tracking app

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  riverpod: ^2.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.66.0
  intl: ^0.18.0